name: Docs

on:
  push:
    paths: ['**.md']
  pull_request:
    paths: ['**.md']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v19
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          globs: '**.md'
          config: .github/lint.markdownlint-cli2.yaml

      - name: Spell check
        run: |
          npm install -g cspell @cspell/dict-en_us @cspell/dict-ru_ru
          cspell --config .github/cspell.json "**/*.md"
